# Generated by Django 4.0.8 on 2023-10-14 14:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infosApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_reduzido', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=200)),
                ('background', models.ImageField(blank=True, null=True, upload_to=core.models.background_directory_path, verbose_name='Background')),
            ],
        ),
    ]
