# Generated by Django 4.2.4 on 2023-10-17 21:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosapp',
            name='logo_sem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.background_directory_path, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='infosapp',
            name='logo_variacao',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.background_directory_path, verbose_name='Logo Variação'),
        ),
        migrations.AddField(
            model_name='infosapp',
            name='logo_verde',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.background_directory_path, verbose_name='Logo Verde'),
        ),
    ]
