# Generated by Django 4.2.4 on 2023-09-13 16:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosapp',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.background_directory_path, verbose_name='Background'),
        ),
    ]
