# Generated by Django 4.2.4 on 2024-01-16 20:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_infosapp_logo_sem_fundo_infosapp_logo_variacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosapp',
            name='background_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.background_directory_path, verbose_name='Background Mobile'),
        ),
    ]
