# Generated by Django 4.2.4 on 2023-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_infosapp_nome_reduzido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosapp',
            name='nome_reduzido',
            field=models.CharField(max_length=50),
        ),
    ]
