# Generated by Django 4.0.8 on 2023-08-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='area_emp',
            field=models.CharField(blank=True, max_length=150, verbose_name='area_emp'),
        ),
    ]
