# Generated by Django 4.2.4 on 2023-08-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_users_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gereno',
            new_name='Genero',
        ),
    ]
