# Generated by Django 4.2.4 on 2023-08-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_area_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='area_emp',
        ),
    ]
