# Generated by Django 4.2.4 on 2023-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_users_fone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_paciente',
            field=models.BooleanField(default=False, verbose_name='É paciente?'),
        ),
    ]
