# Generated by Django 4.2.4 on 2023-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_profile_is_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_paciente',
            field=models.BooleanField(default=False, verbose_name='Você já é paciente?'),
        ),
    ]
