# Generated by Django 4.2.4 on 2023-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Defina a ordem das categorias na sidebar'),
        ),
    ]
