# Generated by Django 4.2.4 on 2023-08-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='link_url',
        ),
    ]
