# Generated by Django 4.2.4 on 2023-09-05 08:31

import conteudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_categoria_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=conteudo.models.categoria_directory_path, verbose_name='Capa'),
        ),
    ]
