# Generated by Django 4.2.4 on 2023-08-09 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudo', '0003_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='gerador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_geradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que gerou a notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que recebe a notificação'),
        ),
    ]
