# Generated by Django 4.2.4 on 2023-08-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_remove_conteudo_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
    ]
