# Generated by Django 4.2.4 on 2023-09-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_categoria_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
