# Generated by Django 4.2.4 on 2023-08-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conteudo', '0004_notificacao_gerador_alter_notificacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='gerador',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
